### ISSUE TITLE
NullReferenceException in Download

### ISSUE THREAD

**Issue by Lamia5566** [iamvishnu-media/Apex-Launcher#34] opened 2020-10-01 16:53 UTC
# Exception Details
System.NullReferenceException: Object reference not set to an instance of an object.
at Apex_Launcher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.6.0.0
* Current Game Version: 
* Install Path: D:\Apex

# Files
* `config.txt`
* D:\Apex:
    * ALPHA 9:
        * Fonts
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * ALPHA 9.1p:
        * Fonts
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * Audio v1:
        * Audio

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by iamvishnu-media** [comment] 2020-10-01 17:37
Duplicate of #33. Please check open issues before creating a new one.

**Closed** 2020-10-01 17:37 UTC
Labels: Duplicate
