### ISSUE TITLE
FileNotFoundException in WinIOError

### ISSUE THREAD

**Issue by ArticPhoenix** [iamvishnu-media/Apex-Launcher#32] opened 2020-09-17 20:07 UTC
# Exception Details
System.IO.FileNotFoundException: Le fichier 'C:\Users\David\Downloads\Versions\VersionManifest.xml' est introuvable.
Nom de fichier : 'C:\Users\David\Downloads\Versions\VersionManifest.xml'
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   à System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   à System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   à System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   à System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   à System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   à System.Xml.XmlTextReaderImpl.OpenUrl()
   à System.Xml.XmlTextReaderImpl.Read()
   à System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   à System.Xml.XmlDocument.Load(XmlReader reader)
   à System.Xml.XmlDocument.Load(String filename)
   à Apex_Launcher.VersionGameFiles.GetAllVersions()
   à Apex_Launcher.VersionGameFiles.FromString(String str)
   à Apex_Launcher.Program.Initialize()
   à Apex_Launcher.Program.Main()

# Configuration
* Current Launcher Version: 1.6.0.0
* Current Game Version: 
* Install Path: C:\Users\David\Downloads

# Files
* `config.txt`
* C:\Users\David\Downloads:

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by iamvishnu-media** [comment] 2020-09-17 20:10
Duplicate of #31. Please check existing issues before reporting.

**Closed by iamvishnu-media** 2020-09-17 20:10 UTC
Labels: Duplicate
