### ISSUE TITLE
DirectoryNotFoundException in WinIOError

### ISSUE THREAD

**Issue by MartelloX** [iamvishnu-media/Apex-Launcher#42] opened 2021-02-05 07:18 UTC
# Exception Details
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Owner\Downloads\Versions\ALPHA 9'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at ApexLauncher.DownloadForm.RecursiveCopy(String sourceDirectory, String destinationDirectory, Boolean overwriteFile)
   at ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.7.0.0
* Current Game Version: ALPHA 9p
* Install Path: C:\Users\Owner\Downloads

# Files
* `config.txt`
* C:\Users\Owner\Downloads:
    * C:\Users\Owner\Downloads\Versions:
        * `Game.rgssad`
    * C:\Users\Owner\Downloads\Versions:
        * `Game.rgssad`

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by iamvishnu-media** [comment] 2021-02-05 16:23
Check your antivirus settings to make sure the downloads aren't being quarantined. This is a duplicate of #36. If you have any additional information to add, do so on the original issue instead of opening a new issue.

**Closed by iamvishnu-media** 2021-02-05 16:23 UTC
