### ISSUE TITLE
Downloading game for the first time on a new windows laptop

### ISSUE THREAD

**Issue by sbbln314159** [iamvishnu-media/Apex-Launcher#38] opened 2021-01-26 02:41 UTC
Hello
As the title says, I'm downloading the game to play from the start on a new laptop.  I dowloaded Apex.Launcher.exe under the October 2 post for Version 1.6.1 and when it opens it offers to download the latest 9.3 version. I clicked yes, and it mostly loaded before throwing this error:

# Exception Details
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Ariel\Downloads\pokemon games\Versions\ALPHA 9'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at ApexLauncher.DownloadForm.RecursiveCopy(String sourceDirectory, String destinationDirectory, Boolean overwriteFile)
   at ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.6.1.0
* Current Game Version: ALPHA 9p
* Install Path: C:\Users\Ariel\Downloads\pokemon games

# Files
* `config.txt`
* C:\Users\Ariel\Downloads\pokemon games:
    * C:\Users\Ariel\Downloads\pokemon games\Versions:
        * `Game.rgssad`

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by iamvishnu-media** [comment] 2021-01-28 15:15
This appears to be a possible duplicate of #36. Make sure to check your antivirus settings to make sure that game files didn't get quarantined. If you have any additional information to add to that issue, please do so there.

**Closed by iamvishnu-media** 2021-01-28 15:15 UTC
